os: linux
dist: xenial
language: java
jdk: openjdk11

#GITHUB_TOKEN
#TELEGRAM_BOT_TOKEN

env:
  global:
  - secure: v0IYlID1QyVUdaKRQA07a8rKS0c0GAkFZzo1l5qyY4jREHNhuqeWq27g1+asJsHHlMpsZXxr6AQWCzZMEa0VGDFtvm0QGVCNEJxl+7Fm7sY81jAvIY3ny11JyT37uQ8GiKDoDoODQ71hI5bTqym85ua9XLfsURpyU5vKY5qMGR+8PTQwZi3I23cuCYYj593lom6XyYsfiMwkKAEdopRp4aJqCHGuAxap6JEZnlV6zHAnWZd2a0Ue5XpGlPwTrjYPJZ/a/bMUR7d1RiEaJRwebVvPw1yW3N+3nzIC/DF1oQ11YXNVBgg2ORTk8rPsi4Ujsyofb1V/4MZ7AFV4T1UnKAw5tIJRTPNTkn7n91YQTcoe42LJRqICxUs+mieX06QLOXoUnzhx8H71GI7F5YC1m3vbXztAIKZZnn7DbS6+r85bnvDDixoZbov8LwfRWK+DW8wbCnPtf0xGL6Wf9jkRQB4qtXPzbTCFAZW6THhJkhrqJ6YaVUQ8g6RRJxEBUL7hNvPtWvICBFx6JSTHS+nBw+jgTZTiMoLBGSy9dMe2GuynUpi+rCffhH9MGRU945nv8J6UnF7wBw8zP91e1kJn5i3Rb08yjF/1lJBTqkzNlSAaThLJMdazK7/a3fDIbSDFLPndiP2Ha3vBuGbBOJvQgpm1M/Yc4bMrDJCXXhOoud8=
  - secure: jNpm5OdgoySYlTv5AEEq3D/ffAmpUhSK+5X9qdNJ1u4sl8GyRs2/ySazdPerowLTX+xZ93TxgjKb7XtKJm4I435MxasJ8VA8Bviu5G/vURygRGb/h+QeUAgMxTvHIszZN8dYEoazs3EmgJJ+n0g74J/vyjQceccpv5hZYNwfqyknJeEiJUtjivH2wZlkem5hXItz3PjN/VMdG/DL6pHnnPmylBdFA/c7UFv2xXVqv88C3I6wtYNlOjLqKPLI2mmMtDFZfQz19/xHjpE/clnfTEHmCU53pQObtkUTZa8Gk9SCSxoFUU4K190C1PKyFvfcN6lsOo+O3az9JIowreRHx7QGfLhUn1jMojKxFii7/4JM05HqPubMZKUh28q362YZQzxCPRvtf0731192mM5w/tCw6bPrOQ9qz5SFu+X5Dgm5ZK8b1ceuU8HCZr9dujUsSaAE+Vd3p58pDiEOEiXYN0ECTu/0a8DC7N2T8OXLpdwlhY9S2FUZGRyd1dc6NpygRu5LObTcY03CgOtuMiQtYbNHWZCdD0hppJGNajwV4BwhOwwEm7rG1YSWY45n1/4HzA9McLJFHAzpvsM0yEcpVykWh3YoOhftH87uShccDx/EQqQ6wpPi9slxp5P8M8aJ3kUFE+u557DE2ud6f5eN7dYhwVlQ+29kK8q0N2S19c0=

#HEROKU

deploy:
  provider: heroku
  app: marketplace-main
  api_key:
    secure: "0BBrD0VFbokCda9TLxlO2PhNfB9dzr3eC43A9YDbEkH+YMw+duW50Lw9hYUHh3SR0NgkaVLsDSMhZY1FtmDLecu9ZkKO89uZJ/CIMXVyGPA0aYjPF8osD0j2ykLki+0OYKVxV4zcjzn8aVJ0EndBkTBoc6setr9nO0+nTic8OfhQygeVjcJYz4hpFP3kscm2wBLBMSdAdxLgUoX5Babqo/kWkMlqCTCcff1X90vNB2DN6y7Au9TnaJW0++31N5csPpKI0nh+jWKc29HNARKg2SHf5dedvjsyOsQ4jxdIDqklAk9tPwTHoHfV9Xd1OuBt4lpHJvfV0EX79B27bVJOQpwtQpC7KmaB+59tgRNVB27qUUfdm1YdqZJ4PpckB4nbCZwzUkosP3lWLdMHk66rlZbUQu4i4n50cCXMEL1LtGhjwO57bmQBnKgP7xRna84L2sk1uTfLncb8grRVfVwDeAZ+xyUcYeET+MQosLaN0wKTS4iejKUxFAeFtbdN+dikVtl31BJipuFsSGHpc0ReL8llnfFMYkuqIjri/Y5on4I5co/QNVaM1akRFEXyDGtzvynBN8G4vo53KX5nMDxa2ZQEqd6/KqQw58RGYSa51mIcSAJ85GF+d5jGwzFq5Ny4ia5dFqBR8ot26fNvVMrgYL96DcnmMou/32Y+r9ZrLCo="

#SONARCLOUD

addons:
  sonarcloud:
    organization: "xxcw"
    token:
      secure: "A5b+4jO4tiweJbBCdeqs3CvY11q6sTjbyOuiXYV059HMOeCD1hlt0QiU0qmEzW9qNx5FHUsOJYsr60w3uI3S31theHeC6A81MAsPaBv3n/qU2iT6pT+Af1vnWqjljVlEtbEo+iTPOZMIC/+lesh9o0wO2842bazwndGzVK9ARWBHMlcgIOHVyEQzG4fZPAGDuJ2yvazTKfCr6bDkBde2dgAw9xb12f1K0eiYwn3fO1A95TY1bTQ2+5b7HdtjyINkhbQPbl8gWEaz77e8pdx+7u6ntOQSdIVzQdLACXoiapMpRM0iM+HkTjrI3wYjPNv53Bdd0MFZXaQg3HO57Eu2TRxhixrPQbJ+caDHfZ5vSN5eXJC4F3wMz3TraF+eqkIQEAB+MYF58bSvzrflSCFhKWggnpBP8J1b7zuutt7wyqfVW9FsSdK+uACjhyEfS2eulOwapNG5sax9W/zsepABIecqmeJDw6kq2lm76u2uMY9/rvxtOqJSsrR3nUQyYCDCjs6LYfPp+JXjLVmjrDGEGBF6uZY0jDYu3VRrQHuqbXE0UIc21DxlbWvVUq3ReLZnJ2NzAM3pADZOm2nUvWJRl3T7ZCFNZge1TK7dkekKae5MLRDChZBYBEzSLfP0IkJjWwSjVh55q1/z6Bo8xmpMJqQoH0cVX6p4aUYOv81OEwg="
script:
    - mvn clean verify sonar:sonar -Pcoverage -X

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:

    #TELEGRAM NOTIFICATION

    - curl -d "chat_id=@travis_server_reports&text=build $TRAVIS_BUILD_NUMBER passed. %0A$TRAVIS_COMMIT_MESSAGE" -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage

    #UPDATE JAVADOC REPORT

    - chmod u+x $HOME/build/xxcw/marketplace/scripts/javadocs.sh
    - bash $HOME/build/xxcw/marketplace/scripts/javadocs.sh