os: linux
dist: xenial
language: java
jdk: openjdk8

env:
  global:
    - secure: cq0XB2pFFvGUgm7cGzUEmv6P9cTlG7bcIwnT9PHithF8rqQKsv4LrGOX1Yhqvo/sVUNOs+tJCOHrGyp1jtzVfjl/E6vYsV+1Ul1dOGwqqb9tv5H0uOC/lt7zjZ5J2uNO55PALsNSdbpuCkIqFeHpBchZYlC1gGrD1VJ/PFsAMfGVCaVEuQv91cQU8Z9QhPFlA8Yv5/sH4L057ZAbb8kc2ZpDJaf+7y/Jaut4Sqhhl9ZDZgsPsdvKcllqeK74BErsEAl+MG0P4Wz8Lhk2xR8tK+7HG6jeNEUsJAbBpUgm/axfT1Y8MIh1ApuLlKonGnNcZSGoELvC+pzzMntS1KCxAp/zPyAAIyCZ9tBOlqBbxAYh20/g3s7+q9C39uIuGK4CdRpo3o0uAYbd+TkK2gwGNuTcOQZ8eiou1EKlyv/0Fj/fa5F6y/Kj4Iyo5NpWZ/QYig4eOyPe4/GdudmxElKYi01yL60YDhOYAbXTQjUsxb3/axZtsopV5CKVPeKZ3NY610dfJA82bb4Ayr1VU1x6O89zByMZprYxXgkGPTiHHTWX36dAS5d9t1nA4IUZa64tziFgz5T3TtZ+yIfQ4WiS/qepHQOITKxkVALuXC47uHov5EQvm8W4vBTElAjfNUeYOToOlYNySsnB6UQyw+0qWdmDmec6QR9VznQNxZOr2ZQ=
    - secure: wPcPnW6SAHU0thUPtYj8SRpyrIZSgCqqc4Vp7L9qZbEObnUqL8A9Hyagk2/O6uvajZR0HV+fl2p5rTX6PbS2xcEAx4YexuUjp/630ZJDsycmxxNHXElX1eyfmpZb4mIB9gGPhriACvAk+eBrsVdX2H8TGOnORNOzwtCy13feDKoGNn5eb5KG/S6U5DnQmGJaQCh8D7+8zjxmGz93o42WNW9WUeXKHfRO/TImWQDgKloFBXKdLJNSA11FXRVIm0yRp9PMb+alKHh7d3cAOgtNAk2qK7a+Y2xPK2uijdxRgyyfByGASJ7f6XIqjtL7C9Qpz0KNXjKlZB3mkb4Zdm8pXtki89QtlCebfzYD3mMerS60pInIgblWG2ymWcQLiyi/xbo7xMLco/bai/9EKSsSE0GaHzJ3Azv0OVf5zvCpHF5/8rWaj3G2LRQXe4EFEDQUBe1HFWpPxflgrUYJQgN/g74RteOO0KR9ShjVcofbEeztShrTLUvl31HnQvhwYyWEb7+3RaZshHCV/THHddK2/Q+mR1T5Xz8oEDS56u5tL0xZHePmiEqKQxpTMRhpz+9gFXEaBYbO0bt1JEsSTUBnJHeahi+X1o9PfWLkVe+yeljB/sc9vYhrkTBNKR8OQBxICoc8rkz8HP23GcJpGvlxZNDBiTNBWBNPpI5B7913W1g=

deploy:
  provider: heroku
  app: xmarketplace
  api_key:
    secure: Di4Uk4qMeVyCaMPtpwCpjRojg+ZHCUC5vA/MUIzZx083ds/Lv3OVeAqVTWARtIgBERz62e6S7NY6BrPF6L0ZXTQ1RST6Aq+92NQHcWhbzpU7Jy0xO7S8i0dwrlxfYlgbD/UG1nRxJoCQbqcHFZFl9/L5gntDNsk8bAWfamrm0z1AoIVQwCfL6ZE4y8fi7pwQczNaJprQ9Ra9U15pjr7LIvlY3Tq9UuqRyepakf/k2qJswezJrh/9ijUCjKrqrUbKQphShKjfbObci9DAid6Xcr5xF40oIwVxsII4/at7mjyX05CTgEZKyXzFtLlHcB4u9yNlR+dH046/95kWOJux4COoS0pQiZPQ/GRXACDJwWkSkJ1Gpr7OO1KJaIFtPbbGPPa+0kTZXe4oA0jrPV4QlANjISaR4njPLy1b9KCsIS7RPZQczT6QFGcAaxiG20uYufenwb8OoVJS4Wj01G18hhfI9Hm4iDdEyqz32W6d6yl3k6i79H64PGxsCtFq4ukcQEXfk/r8FmV96viZAb/eKpPtNw9/ILCWxC6zwoI/RprbnMf12kgNOnOi/6LZOebSkSmfUDHI1CHvmi2yGPFFY5LRbsGIijYxcTat1hRmRxB/M/w1/ycb+n39j29jH+Sw3lLISsrw4Hv0DBBjGcnUqnc8JpUjcfgGofazosceYb0=

addons:
  sonarcloud:
    organization: "alie-n"
    token:
      secure: "0RKOtENnOn74EheCa4IOMfCac+/pfdKQZEEzhB0XF2pV1/srBbifFivSV2bpPq67Z7Oh9wyosVyZcAJeq4IT1vkmU7vyFC27rQ84rfm032oD+B81hPxA73XFQVSxAWXMZV1ypR2ppVA5eJG1aH3V/UNLopaT//NsUrV6mPabSsiFG9tEDQeA1wSupjXYnSpnVoGVT84OpAJ+LQi5RSQnJskC57uc6y4UvtWgtrfMzxCSFYwZGTAJjFjWpLgCO+rHW5pzbUH35MjKw80RFpQMfG2nTwcazmx5FBPFJ0AoPlJ7SvJmbssVGsIivW8X5hm229ytH98n+gmm/OWVDARU7pF/H3JfExJIID6ljwbtY9bHVVkVD3BLTRIN23rRPKpekxAAT9KVOW2hsNyetFnfh3q5Ti7voM2MBWeNdxa7XLLIg2XSiS+3gwybEMZ/QcCbPlrI83hKF6W4/j8aAcupIdOC69yrI4R9qZwvjiueU/h8r0xBvI/hyFbZ6uuDzuz0/R2N5J3ddouLIb/jpNWsE05u+JEkGbawyWffAs3Uao3HFy5OscyEiQ8P0eHD6Z7KGpHUa8PBSQI+zJVbXsxYK4Ias/hnyZXBYEHIAubsvwU15t5iOMTo4Oj02XX0Yxjll1uMyvH+0sshOxjY83qkhVa4E3D60vEMysFj8gZ9T+E="
script:
    - mvn clean verify sonar:sonar -Pcoverage -X

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
    - bash <(curl -s https://codecov.io/bash)

    #TELEGRAM NOTIFICATION

    - curl -d "chat_id=@travis_pro&text=build $TRAVIS_BUILD_NUMBER passed. %0A$TRAVIS_COMMIT_MESSAGE" -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage

    #UPDATE JAVADOC

    - chmod u+x $HOME/build/alie-n/market/scripts/javadocs.sh
    - bash $HOME/build/alie-n/market/scripts/javadocs.sh
