os: linux
dist: xenial
language: java
jdk: openjdk8

env:
  global:
    secure: cq0XB2pFFvGUgm7cGzUEmv6P9cTlG7bcIwnT9PHithF8rqQKsv4LrGOX1Yhqvo/sVUNOs+tJCOHrGyp1jtzVfjl/E6vYsV+1Ul1dOGwqqb9tv5H0uOC/lt7zjZ5J2uNO55PALsNSdbpuCkIqFeHpBchZYlC1gGrD1VJ/PFsAMfGVCaVEuQv91cQU8Z9QhPFlA8Yv5/sH4L057ZAbb8kc2ZpDJaf+7y/Jaut4Sqhhl9ZDZgsPsdvKcllqeK74BErsEAl+MG0P4Wz8Lhk2xR8tK+7HG6jeNEUsJAbBpUgm/axfT1Y8MIh1ApuLlKonGnNcZSGoELvC+pzzMntS1KCxAp/zPyAAIyCZ9tBOlqBbxAYh20/g3s7+q9C39uIuGK4CdRpo3o0uAYbd+TkK2gwGNuTcOQZ8eiou1EKlyv/0Fj/fa5F6y/Kj4Iyo5NpWZ/QYig4eOyPe4/GdudmxElKYi01yL60YDhOYAbXTQjUsxb3/axZtsopV5CKVPeKZ3NY610dfJA82bb4Ayr1VU1x6O89zByMZprYxXgkGPTiHHTWX36dAS5d9t1nA4IUZa64tziFgz5T3TtZ+yIfQ4WiS/qepHQOITKxkVALuXC47uHov5EQvm8W4vBTElAjfNUeYOToOlYNySsnB6UQyw+0qWdmDmec6QR9VznQNxZOr2ZQ=
deploy:
  provider: heroku
  api_key:
    secure: Di4Uk4qMeVyCaMPtpwCpjRojg+ZHCUC5vA/MUIzZx083ds/Lv3OVeAqVTWARtIgBERz62e6S7NY6BrPF6L0ZXTQ1RST6Aq+92NQHcWhbzpU7Jy0xO7S8i0dwrlxfYlgbD/UG1nRxJoCQbqcHFZFl9/L5gntDNsk8bAWfamrm0z1AoIVQwCfL6ZE4y8fi7pwQczNaJprQ9Ra9U15pjr7LIvlY3Tq9UuqRyepakf/k2qJswezJrh/9ijUCjKrqrUbKQphShKjfbObci9DAid6Xcr5xF40oIwVxsII4/at7mjyX05CTgEZKyXzFtLlHcB4u9yNlR+dH046/95kWOJux4COoS0pQiZPQ/GRXACDJwWkSkJ1Gpr7OO1KJaIFtPbbGPPa+0kTZXe4oA0jrPV4QlANjISaR4njPLy1b9KCsIS7RPZQczT6QFGcAaxiG20uYufenwb8OoVJS4Wj01G18hhfI9Hm4iDdEyqz32W6d6yl3k6i79H64PGxsCtFq4ukcQEXfk/r8FmV96viZAb/eKpPtNw9/ILCWxC6zwoI/RprbnMf12kgNOnOi/6LZOebSkSmfUDHI1CHvmi2yGPFFY5LRbsGIijYxcTat1hRmRxB/M/w1/ycb+n39j29jH+Sw3lLISsrw4Hv0DBBjGcnUqnc8JpUjcfgGofazosceYb0=

after_success:
    - bash <(curl -s https://codecov.io/bash)

    #UPDATE JAVADOC

    - |
        if [[ $TRAVIS_COMMIT_MESSAGE != "update javadoc" ]]; then

            - git config --global user.name "travis-ci"
            - git config --global user.email "travis@travis-ci.org"

            - cd $HOME

            - git clone --quiet --branch=master https://$GITHUB_TOKEN@github.com/alie-n/market.git market

            - rm -r $HOME/market/docs/apidocs
            - cp -r $HOME/build/alie-n/market/target/site/apidocs $HOME/market/docs/

            - cd $HOME/market

            - git add .
            - git commit -m "update javadoc"
            - git push https://$GITHUB_TOKEN@github.com/alie-n/market master

            - rm -rf $HOME/market

        fi