os: linux
dist: xenial
language: java
jdk: openjdk11

env:
  global:
  - secure: v0IYlID1QyVUdaKRQA07a8rKS0c0GAkFZzo1l5qyY4jREHNhuqeWq27g1+asJsHHlMpsZXxr6AQWCzZMEa0VGDFtvm0QGVCNEJxl+7Fm7sY81jAvIY3ny11JyT37uQ8GiKDoDoODQ71hI5bTqym85ua9XLfsURpyU5vKY5qMGR+8PTQwZi3I23cuCYYj593lom6XyYsfiMwkKAEdopRp4aJqCHGuAxap6JEZnlV6zHAnWZd2a0Ue5XpGlPwTrjYPJZ/a/bMUR7d1RiEaJRwebVvPw1yW3N+3nzIC/DF1oQ11YXNVBgg2ORTk8rPsi4Ujsyofb1V/4MZ7AFV4T1UnKAw5tIJRTPNTkn7n91YQTcoe42LJRqICxUs+mieX06QLOXoUnzhx8H71GI7F5YC1m3vbXztAIKZZnn7DbS6+r85bnvDDixoZbov8LwfRWK+DW8wbCnPtf0xGL6Wf9jkRQB4qtXPzbTCFAZW6THhJkhrqJ6YaVUQ8g6RRJxEBUL7hNvPtWvICBFx6JSTHS+nBw+jgTZTiMoLBGSy9dMe2GuynUpi+rCffhH9MGRU945nv8J6UnF7wBw8zP91e1kJn5i3Rb08yjF/1lJBTqkzNlSAaThLJMdazK7/a3fDIbSDFLPndiP2Ha3vBuGbBOJvQgpm1M/Yc4bMrDJCXXhOoud8=
  - secure: jNpm5OdgoySYlTv5AEEq3D/ffAmpUhSK+5X9qdNJ1u4sl8GyRs2/ySazdPerowLTX+xZ93TxgjKb7XtKJm4I435MxasJ8VA8Bviu5G/vURygRGb/h+QeUAgMxTvHIszZN8dYEoazs3EmgJJ+n0g74J/vyjQceccpv5hZYNwfqyknJeEiJUtjivH2wZlkem5hXItz3PjN/VMdG/DL6pHnnPmylBdFA/c7UFv2xXVqv88C3I6wtYNlOjLqKPLI2mmMtDFZfQz19/xHjpE/clnfTEHmCU53pQObtkUTZa8Gk9SCSxoFUU4K190C1PKyFvfcN6lsOo+O3az9JIowreRHx7QGfLhUn1jMojKxFii7/4JM05HqPubMZKUh28q362YZQzxCPRvtf0731192mM5w/tCw6bPrOQ9qz5SFu+X5Dgm5ZK8b1ceuU8HCZr9dujUsSaAE+Vd3p58pDiEOEiXYN0ECTu/0a8DC7N2T8OXLpdwlhY9S2FUZGRyd1dc6NpygRu5LObTcY03CgOtuMiQtYbNHWZCdD0hppJGNajwV4BwhOwwEm7rG1YSWY45n1/4HzA9McLJFHAzpvsM0yEcpVykWh3YoOhftH87uShccDx/EQqQ6wpPi9slxp5P8M8aJ3kUFE+u557DE2ud6f5eN7dYhwVlQ+29kK8q0N2S19c0=

after_success:

    #TELEGRAM NOTIFICATION

    - curl -d "chat_id=@travis_pro&text=build $TRAVIS_BUILD_NUMBER passed. %0A$TRAVIS_COMMIT_MESSAGE" -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage

    #UPDATE JAVADOC REPORT

    - chmod u+x $HOME/build/xxcw/marketplace/scripts/javadocs.sh
    - bash $HOME/build/xxcw/marketplace/scripts/javadocs.sh